name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.1, 7.2, 7.3, 7.4]
        lib:
          - { laravel: ^8.0, testbench: ^6.0, composer_flags: --prefer-stable }
          - { laravel: ^7.0, testbench: ^5.0, composer_flags: --prefer-stable }
          - { laravel: ^6.0, testbench: ^4.0, composer_flags: --prefer-stable }
          - { laravel: ^6.0, testbench: ^4.0, composer_flags: --prefer-stable --prefer-lowest }
          - { laravel: 5.8.*, testbench: 3.8.*, composer_flags: --prefer-stable }
        exclude:
          - lib: { laravel: ^8.0, testbench: ^6.0, composer_flags: --prefer-stable }
            php: 7.2
          - lib: { laravel: ^8.0, testbench: ^6.0, composer_flags: --prefer-stable }
            php: 7.1
          - lib: { laravel: ^7.0, testbench: ^5.0, composer_flags: --prefer-stable }
            php: 7.1
          - lib: { laravel: ^6.0, testbench: ^4.0, composer_flags: --prefer-stable }
            php: 7.1
          - lib: { laravel: ^6.0, testbench: ^4.0, composer_flags: --prefer-stable --prefer-lowest }
            php: 7.1
          - lib: { laravel: 5.8.*, testbench: 3.8.*, composer_flags: --prefer-stable }
            php: 8.0
          - lib: { laravel: 5.7.*, testbench: 3.7.*, composer_flags: --prefer-stable }
            php: 8.0
          - lib: { laravel: 5.6.*, testbench: 3.6.*, composer_flags: --prefer-stable }
            php: 8.0

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Adjust package versions
        run: |
          composer require "laravel/framework:${{ matrix.lib.laravel }}" --dev --no-update ${{ matrix.lib.composer_flags }}
          composer require "orchestra/testbench:${{ matrix.lib.testbench }}" --dev --no-update ${{ matrix.lib.composer_flags }}
          composer update ${{ matrix.lib.composer_flags }}
      - name: Lunch docker containers
        run: |
          cp docker-compose-ci.yml docker-compose.yml
          docker-compose up -d
          sh -c 'docker-compose logs -f mysql | { sed "/mysqld: ready for connections/ q" && kill $$ ;}' || :
        env:
          PHP_VERSION: ${{ matrix.php }}
      - run: docker-compose exec -T php sh -c 'cd /code; vendor/bin/phpunit'
